name: Update last
on:
  push
jobs:
  last:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: run last
        run: bash last.sh
      - name: Commit last
        uses: EndBug/add-and-commit@v7
        with:
          author_name: Palinsesto
          message: 'Aggiornati palinsesti'
          add: 'last.json'
